### ISSUE TITLE
publicwww has a error bug

### ISSUE THREAD

**Issue by wjlin0** [projectdiscovery/uncover#385]
### uncover version: 
latest
### Current Behavior:
我发现在 publicwww.go 中，如果它 的key 是可以错误的或者不可用的时候，publicwww的api接口会返回 `API available for paid search results only`, 我们的代码还是会正常运行，并且 publicwww Query 函数不会终止就会一直无限循环 就像下面这个截图一样
<img width="1133" alt="image" src="https://github.com/projectdiscovery/uncover/assets/91306421/429e49a5-6198-4399-a7eb-e45e58898e1b">
我开始寻找原因，终于我发现 `sources.GetHostname(record[0])` 处理 hostname 时 会返回一个空的 "" ,并且 err 为 nil，我进一步发现
url.Parse(u) 在处理 `u="API available for paid search results only"`的时候 他是能够正常返回一个结构体的 它的hostname就为 ""，但是它的path 就是 "API%20available%20for%20paid%20search%20results%20only"

### Anything else:
在我fork的[uncover](https://github.com/wjlin0/uncover/commit/1c8628ee91cb8e63c299f90127ce3aa265fda660) 已经修复了这个问题，可以提供一个参考

**Comment by olearycrew** [comment]
translate.google.com translation

I found that in publicwww.go, if its key is wrong or unavailable, the publicwww api interface will return API available for paid search results only, our code will still run normally, and the publicwww Query function will not When terminated, it will continue to loop infinitely, just like the screenshot below.
image
I started looking for the reason, and finally I found that sources.GetHostname(record[0]) will return an empty "" when processing hostname, and err is nil. I further found
When url.Parse(u) handles u="API available for paid search results only", it can return a structure normally. Its hostname is "", but its path is "API%20available%20for%" 20paid%20search%20results%20only"

Anything else:
This problem has been fixed in my fork's uncover and can provide a reference.

**Comment by dogancanbakir** [comment]
Although they offer a free plan, the API returns "API available for paid search results only". I have reached out to them for clarification and will keep you updated.

**Comment by dogancanbakir** [comment]
@wjlin0, I missed an important aspect while testing the API. Unfortunately, API access is not available for non-paid accounts. Can you confirm if you're using a paid account?
![image](https://github.com/projectdiscovery/uncover/assets/65292895/51fffefb-d953-478e-9cda-bae821ea2d02)

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issue still persists with a paid account.
